//
//  ViewController.m
//  ScrollViewStickyAutolayout
//
//  Created by Howard Yeh on 2015-01-20.
//  Copyright (c) 2015 Howard Yeh. All rights reserved.
//

#import "ViewController.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.scrollView.contentSize = self.imageView.frame.size;
    // Do any additional setup after loading the view, typically from a nib.
}

- (void)viewDidAppear:(BOOL)animated {
    // still resizes back to original size after removing WxH constraints generated by the system..
    [self.imageView removeConstraints: self.imageView.constraints];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (IBAction)enbiggen:(id)sender {
    self.imageView.frame = (CGRect) {0,0,200,800};
    self.scrollView.contentSize = self.imageView.frame.size;
    // it resizes back to original size after scrolling.
}

@end
